language: java
jdk: openjdk8

script:
- ./mvnw clean install -B

sudo: required

services:
  - docker

after_success:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- export IMAGE_NAME=xmrcmx/springcicdheroku
- docker build -t $IMAGE_NAME:latest .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:latest
- docker images;
- docker push $IMAGE_NAME:latest