sudo: required
language: java
jdk: openjdk8

services:
  - docker

script:
  - "./mvnw clean install -B"

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export IMAGE_NAME=xmrcmx/springcicdheroku
  - docker build -t $IMAGE_NAME:emir .
  - docker push $IMAGE_NAME:emir

  - openssl aes-256-cbc -K $encrypted_d894e0139945_key -iv $encrypted_d894e0139945_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host 172.105.65.197\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh -i ./deploy_key root@172.105.65.197 "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && (docker container stop springcicdheroku || true) && (docker container rm springcicdheroku || true) && docker pull xmrcmx/springcicdheroku:emir && docker run --name springcicdheroku -p 8080:8080 -d xmrcmx/springcicdheroku:emir"
