sudo: required
language: java
jdk: openjdk8

services:
  - docker

script:
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

addons:
  sonarcloud:
    organization: "xmrcmx"
    token:
      secure: "f0c6523a68a52abbb4697c4df9c35fd7efdfbd32"



after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export IMAGE_NAME=xmrcmx/springcicdheroku
  - docker build -t $IMAGE_NAME:emir .
  - docker push $IMAGE_NAME:emir

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: springcicdheroku
