language: java
jdk: openjdk8

sudo: required

services:
  - docker

after_success:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- export IMAGE_NAME=xmrcmx/springcicdheroku
- docker build -t $IMAGE_NAME:emir .
- docker push $IMAGE_NAME:emir